version: '3'
services:
  magic_mirror:
    image: magic_mirror
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: magic_mirror
    environment:
      - DISPLAY=<YOUR_IP_ADDRESS>:0
      # - MQTT_BROKER_HOST=mqtt_broker
      # - MQTT_BROKER_PORT=1883
    volumes:
      - ./config:/opt/magicmirror/config
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    networks:
      - mqtt_network
    privileged: true

    restart: unless-stopped


networks:
  mqtt_network:
    external: true
