version: '3'
services:
  magic_mirror:
    image: magic_mirror
    build: 
      context: .
      dockerfile: dockerfile
    container_name: magic_mirror
    environment:
      - DISPLAY=192.168.178.21:0
    ports:
      - "8080:8080"
    volumes:
      - ./config:/opt/magicmirror/config
    restart: unless-stopped