version: '3'
services:
  magic_mirror:
    image: magic_mirror
    build: 
      context: .
      dockerfile: dockerfile
    container_name: magic_mirror
    environment:
      - DISPLAY=192.168.178.21:0
    ports:
      - "8080:8080"
    volumes:
      - ./config:/opt/magicmirror/config
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
    privileged: true

    restart: unless-stopped
