version: '3'
services:
  magic_mirror:
    image: magic_mirror
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: magic_mirror
    environment:
      - DISPLAY=:0
    volumes:
      - ./config:/opt/magicmirror/config
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    # networks:
    #   - mqtt_network
    network_mode: host

    privileged: true
    
    restart: unless-stopped


